version: 2.1

executors:
  github-publisher:
    docker:
      - image: cibuilds/github:0.10

commands:
  store-artifacts:
    steps:
      - persist_to_workspace:
          root: ./
          paths:
            - ./.assets/*
  restore-artifacts:
    steps:
      - attach_workspace:
          at: ./
jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run:
          command: mkdir -p "./.assets/" && echo "test" > ./.assets/test.test
      - store-artifacts
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - restore-artifacts
      - run:
          command: echo "test2" > ./.assets/test2.test
      - store-artifacts
  publish:
    executor: github-publisher
    steps:
      - restore-artifacts
      - run: |
          ls -lah .
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_TAG} ./.assets/test.test
workflows:
  version: 2

  test:
    jobs:
      - test:
          filters:
            branches:
              only: /.+/
            tags:
              only: /.+/
      - publish:
          requires: [test]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.+/
