on:
  workflow_call:
jobs:
  call-workflow-passing-data:
    uses: funivan/test/.github/workflows/updater.yml@master
    with:
      repository: funivan/test
    secrets:
      token: ${{ secrets.SCALA_STEWARD_GITHUB_TOKEN }}
