on:
  push:
jobs:
  call-workflow-passing-data:
    - uses: actions/checkout@v2
    - uses: funivan/test/.github/workflows/reusable-workflow.yml@master
      with:
        repository: funivan/test
        token: "${{ secrets.SCALA_STEWARD_GITHUB_TOKEN }}"
