on:
  push:
jobs:
  call-workflow-passing-data:
    uses: funivan/test/.github/reusable-workflow.yml@master
    with:
      repository: funivan/test
    secrets:
      token: ${{ secrets.SCALA_STEWARD_GITHUB_TOKEN }}
