on: push
name: Fast prototype
jobs:
  createPR:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Create PR
        uses: funivan/github-autopr@0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: .head_commit.message .*#pr.*