on:
  workflow_call:
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
    - name: Launch Scala Steward
      uses: scala-steward-org/scala-steward-action@v2
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        author-email: "alotofall@gmail.com"
        author-name: "Ivan Shcherbak"
